CREATE TABLE Telefonnummer (
    Nummer VARCHAR2(15) PRIMARY KEY,
    CHECK (
        LENGTH(TRIM(Nummer)) BETWEEN 7 AND 15
     AND REGEXP_LIKE(TRIM(Nummer), '^\+?[0-9]{7,15}$')
    )
);

CREATE TABLE Filiale (
    Filialnummer NUMBER(4)   PRIMARY KEY,
    Stadt        VARCHAR2(80) NOT NULL
);

CREATE TABLE Modellinfo (
    Marke  VARCHAR2(60) PRIMARY KEY,   -- determinant, now the key
    Modell VARCHAR2(60) NOT NULL
);

CREATE TABLE Fahrzeug (
    Fahrzeug_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
               PRIMARY KEY,
    Marke  VARCHAR2(60) NOT NULL,
    Baujahr NUMBER(4)   NOT NULL CHECK (Baujahr >= 1950),

    FOREIGN KEY (Marke)
        REFERENCES Modellinfo(Marke)
);

CREATE TABLE Kunde (
    Fuehrerscheinnummer CHAR(20) PRIMARY KEY,
    Name                VARCHAR2(100) NOT NULL,
    Geburtsdatum        DATE          NOT NULL,
    Nummer              VARCHAR2(15)  NOT NULL,      -- candidate key
    UNIQUE (Nummer),
    FOREIGN KEY (Nummer)
      REFERENCES Telefonnummer(Nummer)               -- NO ACTION
);

CREATE TABLE Mitarbeiter (
    Personalnummer NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
                  PRIMARY KEY,
    Name           VARCHAR2(100) NOT NULL,
    Filialnummer   NUMBER(4),                        -- nullable (SET NULL)
    Nummer         VARCHAR2(15)  NOT NULL,           -- candidate key
    UNIQUE (Nummer),
    FOREIGN KEY (Filialnummer)
      REFERENCES Filiale(Filialnummer)
      ON DELETE SET NULL,                            -- SET NULL demo
    FOREIGN KEY (Nummer)
      REFERENCES Telefonnummer(Nummer)               -- NO ACTION
);

CREATE TABLE Inspektionsmitarbeiter (
    Personalnummer NUMBER PRIMARY KEY,
    FOREIGN KEY (Personalnummer)
      REFERENCES Mitarbeiter(Personalnummer)
      ON DELETE CASCADE
);

CREATE TABLE Ist_boss_von (
    ManagerID NUMBER PRIMARY KEY,
    FOREIGN KEY (ManagerID)
      REFERENCES Mitarbeiter(Personalnummer)
      ON DELETE CASCADE                   -- CASCADE demo
);

CREATE TABLE Reservierung (
    Fuehrerscheinnummer CHAR(20) NOT NULL,    --- NOT NULL demo
    Reservierungsnummer     NUMBER   NOT NULL,
    Reservierungsdatum  DATE DEFAULT TRUNC(SYSDATE),    --- DEFAULT demo
    EndeDatum           DATE NOT NULL,
    CHECK (EndeDatum > Reservierungsdatum),
    PRIMARY KEY (Fuehrerscheinnummer, Reservierungsnummer),
    FOREIGN KEY (Fuehrerscheinnummer)
      REFERENCES Kunde(Fuehrerscheinnummer)
      ON DELETE CASCADE
);

CREATE TABLE Vermieten (
    Fuehrerscheinnummer CHAR(20) NOT NULL,
    Personalnummer      NUMBER   NOT NULL,
    Fahrzeug_ID         NUMBER   NOT NULL,
    PRIMARY KEY (Fuehrerscheinnummer, Personalnummer, Fahrzeug_ID),
    FOREIGN KEY (Fuehrerscheinnummer)
      REFERENCES Kunde(Fuehrerscheinnummer),
    FOREIGN KEY (Personalnummer)
      REFERENCES Mitarbeiter(Personalnummer),
    FOREIGN KEY (Fahrzeug_ID)
      REFERENCES Fahrzeug(Fahrzeug_ID)
);

CREATE TABLE Ueberpruefen (
    Fahrzeug_ID    NUMBER NOT NULL,
    Personalnummer NUMBER NOT NULL,
    PRIMARY KEY (Fahrzeug_ID, Personalnummer),
    FOREIGN KEY (Fahrzeug_ID)
      REFERENCES Fahrzeug(Fahrzeug_ID)
      ON DELETE CASCADE,
    FOREIGN KEY (Personalnummer)
      REFERENCES Mitarbeiter(Personalnummer)
      ON DELETE CASCADE
);

CREATE TABLE Hat_Filiale (
    Filialnummer NUMBER(4)   NOT NULL,
    Nummer       VARCHAR2(15) NOT NULL,
    PRIMARY KEY (Filialnummer, Nummer),
    FOREIGN KEY (Filialnummer)
      REFERENCES Filiale(Filialnummer)
      ON DELETE CASCADE,
    FOREIGN KEY (Nummer)
      REFERENCES Telefonnummer(Nummer)
      ON DELETE CASCADE
);