
DROP TABLE Hat_Filiale             CASCADE CONSTRAINTS PURGE;
DROP TABLE Ueberpruefen            CASCADE CONSTRAINTS PURGE;
DROP TABLE Vermieten               CASCADE CONSTRAINTS PURGE;
DROP TABLE Reservierung            CASCADE CONSTRAINTS PURGE;
DROP TABLE Ist_boss_von            CASCADE CONSTRAINTS PURGE;
DROP TABLE Inspektionsmitarbeiter  CASCADE CONSTRAINTS PURGE;
DROP TABLE Mitarbeiter             CASCADE CONSTRAINTS PURGE;
DROP TABLE Kunde                   CASCADE CONSTRAINTS PURGE;
DROP TABLE Fahrzeug                CASCADE CONSTRAINTS PURGE;
DROP TABLE Modellinfo              CASCADE CONSTRAINTS PURGE;
DROP TABLE Filiale                 CASCADE CONSTRAINTS PURGE;
DROP TABLE Telefonnummer           CASCADE CONSTRAINTS PURGE;
